### ISSUE TITLE
Controller Tests with ScalaTest

### ISSUE THREAD

**Issue by phancox** [phosphene/play-slick-silhouette-scalatest#1]
Have you been able to get the controller tests working with scalatest; I see the controller test is the original specs2 test?

THANKS

**Comment by phosphene** [comment]
Hello,

I have not looked at this project in some time. I'm taking a look now.

**Comment by phosphene** [comment]
I just added a new example controller spec that uses scalatest and some of the previous idioms.

**Comment by phancox** [comment]
Thanks for adding that example.  I've just started working with play and silhouette and wanted to use scalatest rather than specs2 since that appears to be the play "preferred" test framework as of the 2.5 release.  I did figure it out late last night but there do appear to be a lot of people looking for guidance on using scalatest with silhouette.
